{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPeYVIsU9D0YErTqZEY4kFR",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/carneiro-santos/dataton_fase_5_/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 383
        },
        "id": "xFsTBZvIRi2q",
        "outputId": "d0a966ec-1728-4988-f5d7-7eba150315da"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "No module named 'streamlit'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipykernel_3345/1403387443.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mstreamlit\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mst\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mjoblib\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'streamlit'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ],
          "errorDetails": {
            "actions": [
              {
                "action": "open_url",
                "actionText": "Open Examples",
                "url": "/notebooks/snippets/importing_libraries.ipynb"
              }
            ]
          }
        }
      ],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "import joblib\n",
        "import os\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "\n",
        "# Configuração da página\n",
        "st.set_page_config(\n",
        "    page_title=\"Passos Mágicos - Predição de Risco Educacional\",\n",
        "    page_icon=\"📚\",\n",
        "    layout=\"wide\",\n",
        "    initial_sidebar_state=\"expanded\"\n",
        ")\n",
        "\n",
        "# Carregar modelo e scaler\n",
        "@st.cache_resource\n",
        "def load_model_and_scaler():\n",
        "    base_dir = os.path.dirname(os.path.dirname(__file__))\n",
        "    model_path = os.path.join(base_dir, 'src', 'optimized_model.pkl')\n",
        "    scaler_path = os.path.join(base_dir, 'src', 'scaler_v2.pkl')\n",
        "    feature_cols_path = os.path.join(base_dir, 'src', 'feature_cols.pkl')\n",
        "\n",
        "    model = joblib.load(model_path)\n",
        "    scaler = joblib.load(scaler_path)\n",
        "    feature_cols = joblib.load(feature_cols_path)\n",
        "\n",
        "    return model, scaler, feature_cols\n",
        "\n",
        "# Função para fazer predição\n",
        "def predict_risk(model, scaler, feature_cols, input_data):\n",
        "    \"\"\"Faz a predição de risco com base nos dados de entrada.\"\"\"\n",
        "    # Criar DataFrame com as features\n",
        "    df_input = pd.DataFrame([input_data], columns=feature_cols)\n",
        "\n",
        "    # Normalizar\n",
        "    df_input_scaled = scaler.transform(df_input)\n",
        "\n",
        "    # Predição\n",
        "    prediction = model.predict(df_input_scaled)[0]\n",
        "    prediction_proba = model.predict_proba(df_input_scaled)[0]\n",
        "\n",
        "    return prediction, prediction_proba\n",
        "\n",
        "# Interface principal\n",
        "def main():\n",
        "    # Carregar modelo\n",
        "    model, scaler, feature_cols = load_model_and_scaler()\n",
        "\n",
        "    # Título e descrição\n",
        "    st.title(\"📚 Passos Mágicos - Sistema de Predição de Risco Educacional\")\n",
        "    st.markdown(\"\"\"\n",
        "    Este sistema utiliza **Machine Learning** para identificar alunos em risco de defasagem educacional,\n",
        "    permitindo intervenções proativas e personalizadas.\n",
        "    \"\"\")\n",
        "\n",
        "    # Sidebar para entrada de dados\n",
        "    st.sidebar.header(\"📝 Dados do Aluno\")\n",
        "\n",
        "    # Inputs principais\n",
        "    st.sidebar.subheader(\"Indicadores Principais\")\n",
        "    ida = st.sidebar.slider(\"IDA - Desempenho Acadêmico\", 0.0, 10.0, 7.0, 0.1)\n",
        "    ieg = st.sidebar.slider(\"IEG - Engajamento\", 0.0, 10.0, 7.5, 0.1)\n",
        "    ips = st.sidebar.slider(\"IPS - Aspectos Psicossociais\", 0.0, 10.0, 6.5, 0.1)\n",
        "    ipp = st.sidebar.slider(\"IPP - Aspectos Psicopedagógicos\", 0.0, 10.0, 7.0, 0.1)\n",
        "    iaa = st.sidebar.slider(\"IAA - Autoavaliação\", 0.0, 10.0, 8.0, 0.1)\n",
        "    ipv = st.sidebar.slider(\"IPV - Ponto de Virada\", 0.0, 10.0, 7.5, 0.1)\n",
        "\n",
        "    # Inputs adicionais\n",
        "    st.sidebar.subheader(\"Informações Adicionais\")\n",
        "    ano = st.sidebar.selectbox(\"Ano\", [2022, 2023, 2024], index=2)\n",
        "    genero = st.sidebar.selectbox(\"Gênero\", [\"Feminino\", \"Masculino\", \"NAO_INFORMADO\"])\n",
        "    fase = st.sidebar.selectbox(\"Fase\", [\"ALFA\", \"FASE 1\", \"FASE 2\", \"FASE 3\", \"FASE 4\", \"FASE 5\", \"FASE 6\", \"FASE 7\", \"FASE 8\", \"NAO_INFORMADO\"])\n",
        "\n",
        "    # Encoding de variáveis categóricas (simplificado)\n",
        "    genero_encoded = {\"Feminino\": 0, \"Masculino\": 1, \"NAO_INFORMADO\": 2}[genero]\n",
        "    fase_encoded = {\"ALFA\": 0, \"FASE 1\": 1, \"FASE 2\": 2, \"FASE 3\": 3, \"FASE 4\": 4, \"FASE 5\": 5, \"FASE 6\": 6, \"FASE 7\": 7, \"FASE 8\": 8, \"NAO_INFORMADO\": 9}[fase]\n",
        "\n",
        "    # Calcular features derivadas\n",
        "    ida_ieg_interaction = ida * ieg\n",
        "    ipp_ips_interaction = ipp * ips\n",
        "    ida_ieg_ratio = ida / (ieg + 0.001)\n",
        "    mean_indicators = np.mean([ida, ieg, ips, ipp, iaa, ipv])\n",
        "\n",
        "    # Features temporais (valores padrão para novos alunos)\n",
        "    ida_lag1 = st.sidebar.number_input(\"IDA (Ano Anterior)\", 0.0, 10.0, ida, 0.1)\n",
        "    ieg_lag1 = st.sidebar.number_input(\"IEG (Ano Anterior)\", 0.0, 10.0, ieg, 0.1)\n",
        "    ips_lag1 = st.sidebar.number_input(\"IPS (Ano Anterior)\", 0.0, 10.0, ips, 0.1)\n",
        "\n",
        "    ida_delta = ida - ida_lag1\n",
        "    ieg_delta = ieg - ieg_lag1\n",
        "\n",
        "    # Montar vetor de features\n",
        "    input_data = [\n",
        "        ida, ieg, ips, ipp, iaa, ipv,\n",
        "        ida_ieg_interaction, ipp_ips_interaction, ida_ieg_ratio,\n",
        "        mean_indicators, ida_lag1, ieg_lag1, ips_lag1,\n",
        "        ida_delta, ieg_delta, genero_encoded, fase_encoded, ano\n",
        "    ]\n",
        "\n",
        "    # Botão de predição\n",
        "    if st.sidebar.button(\"🔮 Prever Risco\", type=\"primary\"):\n",
        "        # Fazer predição\n",
        "        prediction, prediction_proba = predict_risk(model, scaler, feature_cols, input_data)\n",
        "\n",
        "        # Exibir resultados\n",
        "        st.header(\"📊 Resultado da Predição\")\n",
        "\n",
        "        col1, col2, col3 = st.columns(3)\n",
        "\n",
        "        with col1:\n",
        "            st.metric(\"Classificação\", \"Alto Risco\" if prediction == 1 else \"Baixo Risco\",\n",
        "                     delta=\"Atenção\" if prediction == 1 else \"OK\", delta_color=\"inverse\")\n",
        "\n",
        "        with col2:\n",
        "            st.metric(\"Probabilidade de Risco\", f\"{prediction_proba[1]*100:.1f}%\")\n",
        "\n",
        "        with col3:\n",
        "            st.metric(\"Confiança\", f\"{max(prediction_proba)*100:.1f}%\")\n",
        "\n",
        "        # Gráfico de probabilidades\n",
        "        st.subheader(\"📈 Distribuição de Probabilidades\")\n",
        "        fig, ax = plt.subplots(figsize=(8, 4))\n",
        "        labels = ['Baixo Risco', 'Alto Risco']\n",
        "        colors = ['#28a745', '#dc3545']\n",
        "        ax.bar(labels, prediction_proba, color=colors, alpha=0.7)\n",
        "        ax.set_ylabel('Probabilidade')\n",
        "        ax.set_ylim(0, 1)\n",
        "        ax.set_title('Probabilidade de Risco de Defasagem')\n",
        "        for i, v in enumerate(prediction_proba):\n",
        "            ax.text(i, v + 0.02, f'{v*100:.1f}%', ha='center', fontweight='bold')\n",
        "        st.pyplot(fig)\n",
        "\n",
        "        # Recomendações\n",
        "        st.subheader(\"💡 Recomendações\")\n",
        "        if prediction == 1:\n",
        "            st.error(\"\"\"\n",
        "            **Aluno em Alto Risco de Defasagem**\n",
        "\n",
        "            Recomendações:\n",
        "            - 🎯 **Intervenção Imediata**: Agendar reunião com o aluno e responsáveis\n",
        "            - 📚 **Reforço Acadêmico**: Oferecer aulas de reforço nas disciplinas com baixo desempenho\n",
        "            - 🤝 **Mentoria**: Designar um mentor para acompanhamento próximo\n",
        "            - 🧠 **Suporte Psicopedagógico**: Avaliar necessidade de apoio psicológico ou pedagógico\n",
        "            - 📊 **Monitoramento Frequente**: Acompanhar evolução semanalmente\n",
        "            \"\"\")\n",
        "        else:\n",
        "            st.success(\"\"\"\n",
        "            **Aluno com Baixo Risco de Defasagem**\n",
        "\n",
        "            Recomendações:\n",
        "            - ✅ **Manutenção**: Continuar com as atividades regulares do programa\n",
        "            - 🌟 **Estímulo**: Incentivar participação em atividades de liderança\n",
        "            - 📈 **Desafios**: Propor atividades mais desafiadoras para estimular crescimento\n",
        "            - 👥 **Mentoria Reversa**: Considerar o aluno como mentor de colegas em risco\n",
        "            \"\"\")\n",
        "\n",
        "        # Análise de indicadores\n",
        "        st.subheader(\"📋 Análise Detalhada dos Indicadores\")\n",
        "\n",
        "        indicators_df = pd.DataFrame({\n",
        "            'Indicador': ['IDA', 'IEG', 'IPS', 'IPP', 'IAA', 'IPV'],\n",
        "            'Valor': [ida, ieg, ips, ipp, iaa, ipv],\n",
        "            'Status': [\n",
        "                '✅ Adequado' if ida >= 7 else '⚠️ Atenção' if ida >= 5 else '❌ Crítico',\n",
        "                '✅ Adequado' if ieg >= 7 else '⚠️ Atenção' if ieg >= 5 else '❌ Crítico',\n",
        "                '✅ Adequado' if ips >= 7 else '⚠️ Atenção' if ips >= 5 else '❌ Crítico',\n",
        "                '✅ Adequado' if ipp >= 7 else '⚠️ Atenção' if ipp >= 5 else '❌ Crítico',\n",
        "                '✅ Adequado' if iaa >= 7 else '⚠️ Atenção' if iaa >= 5 else '❌ Crítico',\n",
        "                '✅ Adequado' if ipv >= 7 else '⚠️ Atenção' if ipv >= 5 else '❌ Crítico'\n",
        "            ]\n",
        "        })\n",
        "\n",
        "        st.dataframe(indicators_df, use_container_width=True)\n",
        "\n",
        "    # Informações sobre o modelo\n",
        "    with st.expander(\"ℹ️ Sobre o Modelo\"):\n",
        "        st.markdown(\"\"\"\n",
        "        ### Modelo Preditivo de Risco Educacional\n",
        "\n",
        "        **Algoritmo**: Gradient Boosting Classifier (Otimizado)\n",
        "\n",
        "        **Performance**:\n",
        "        - ROC-AUC Score: 0.7020\n",
        "        - Acurácia: 70%\n",
        "\n",
        "        **Features Mais Importantes**:\n",
        "        1. Razão IDA/IEG (Desempenho vs Engajamento)\n",
        "        2. Ano\n",
        "        3. Fase\n",
        "        4. IDA (Desempenho Acadêmico)\n",
        "        5. IEG (Engajamento)\n",
        "\n",
        "        **Interpretação**:\n",
        "        O modelo utiliza uma combinação de indicadores acadêmicos, psicossociais e psicopedagógicos\n",
        "        para identificar padrões que antecedem quedas de desempenho ou aumento da defasagem.\n",
        "        \"\"\")\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ]
}